### ISSUE TITLE
How to load firmware

### ISSUE THREAD

**Issue by killboxalpha** [dekuNukem/kbord#2]
In the video you show some jumpers on the header and a loading bar. Could you elaborate? I have build one and I've hit a wall on how to load anything on the chip. This is the first time I've programmed a chip outside of some Atmegas and I just use a arduino board with a socket.

**Comment by dekuNukem** [comment]
I did write a short guide on how to upload firmware in another repo, take a look:

https://github.com/dekuNukem/exixe/blob/master/making_some.md
