### ISSUE TITLE
Build details

### ISSUE THREAD

**Issue by disfenoid** [dekuNukem/kbord#6]
Hi, i would like to try to build kbord. As i can see, version described in readme is different from current version of the board. So i have a few questions:
* Is current version of the board is working, or i should use version from specific commit?
* I noticed that now usb type-c used instead of micro, is there any other changes in BOM?
* I'm not a big fan of rgb, will the board work if i will just not solder them?

**Comment by dekuNukem** [comment]
Hi disfenoid:

The new version of the board is fully working, I have been using one myself. 

As for the BOM, USB connector is different, the four pushbuttons are different, and rotary encoders are removed. I think everything else is the same. I'll take a photo of the new board and update the BOM later today. 

The board will work fine if you don't solder the RGB LEDs

**Comment by dekuNukem** [comment]
Here are the photos of the current version:

![whatever](https://i.imgur.com/Qc8oEri.jpg)

![whatever](https://i.imgur.com/zX19Eds.jpg)

I'll update the BOM tomorrow.

**Comment by disfenoid** [comment]
Great, thank you!

**Comment by dekuNukem** [comment]
BOM is here: https://github.com/dekuNukem/kbord/blob/master/pcb/kbord_v2_bom.xlsx

**Comment by NeverMinde** [comment]
> BOM is here: https://github.com/dekuNukem/kbord/blob/master/pcb/kbord_v2_bom.xlsx


Hi, I am trying to build kbord but I got some questions about oled screen connector in 2nd version of your PCB. The 30pin wire bus of 0.96" oled screen have  got 1mm step but PCB pads have got 0.5mm step. So finally question:  
How do you solve this problem?
Can you attach some photo of backside with connected screen?

**Comment by disfenoid** [comment]
@Ep1quell, I ordered this display and connector: aliexpress.com/item/4000375678671.html, but didn't try yet (still waiting for delivery).

**Comment by Ep1quell** [comment]
@disfenoid , with your help I found one more link, here it is: https://s.click.aliexpress.com/e/bd6hKgeO
The main difference is driver IC. In first version of BOM deku said that he using oled with ssd1306 so I think that this will be better cause there is SH1106 in your link

**Comment by dekuNukem** [comment]
This one looks like the OLED that I used:

https://www.aliexpress.com/item/32950730252.html

1.3 inch, 30pin FPC connecter, SSH1106 controller.

**Comment by dekuNukem** [comment]
this listing comes with the FPC connector as well, and also detailed drawings:

https://www.aliexpress.com/item/4000350633981.html

make sure the 30-pin FPC connector is top-contact type,

**Comment by kow** [comment]
do you have any details on the new buttons and usb connector?

**Comment by dekuNukem** [comment]
you can find it here:

https://github.com/dekuNukem/kbord/blob/master/build_it_yourself.md

I significantly updated build details today, hope that helps!
